### PR TITLE
Remove url-unshort

### PR DESCRIPTION
**Pull request by mifi**
`url-unshort` hangs forever and causes memory leak when trying to unshorten an non-shortened url
https://github.com/nodeca/url-unshort/issues/9
This also changes behavior a little bit (hence tests updated)
and `tall` has an issue where it incorrectly resolves some old http-only URLs
see https://github.com/lmammino/tall/issues/19#issuecomment-812575400

TBH I'm not sure if this PR is the right way to do it. URLs could instead be unshortened in the client when shown (in the react statuspage), thus not risking the backend leaking memory.
Or we could not unshorten URLs at all in the backend, because it is error-prone and a bit risky in terms of potential future memory leak issues like this.

### CODE REVIEW

**Review by juliangruber — APPROVED** [review]
LGTM, I don't think this feature was relevant for TSP anyway, and doesn't seem used in another place.

Kick ass investigation work, Mikeal "The Memory Unleaker" Finstad 🙇

**Comment by juliangruber** [comment]
I agree that if we decide to bring back this feature, we could do it client side

**Comment by kvz** [comment]
Very nice work Mikael, thank you. One question, can we make unshortening an opt-in? It is currently used to create more unshorten URLs for: https://transloadit.com/love/. This is done in a one-off import cli script so any hangs or leaks won't be a big problem, and it results in direct unfurled URLs, this makes it easier to see what the tweet was about in one look, what's going to happen when you click a link, and also prevents going through twitter's tracking system should folks want to click on them.

**Comment by mifi** [comment]
I added an `unsorten` bool as the second argument now (default `true`).

Btw should we have github actions to run tests/lint for this repo on PR or push to master?

**Comment by kvz** [comment]
> I added an `unsorten` bool as the second argument now (default `true`).

Awesome :)

> Btw should we have github actions to run tests/lint for this repo on PR or push to master?

Much yes!

**Comment by kvz** [comment]
```bash
Successfully published:
 - @transloadit/enrich-tweet@0.0.14
lerna success published 1 package
```

**Pull request merged**
