### PR TITLE
Turbo

### PR DESCRIPTION
**Pull request by kvz**

### CODE REVIEW

**Comment by Murderlon** [comment]
I wonder if turbo is actually needed as `tsc` already has caching so re-running it when only one package changed is still fast. I recently removed it from tus-node-server. @remcohaszing may have some thoughts on this as well.

**Comment by kvz** [comment]
It's not just about speeding up a lerna powered tsc run tho is it?

A full test run just went from 20+ seconds to 0.2 for instance:


CleanShot 2024-11-13 at 11 43 07@2x

**Comment by Murderlon** [comment]
It's not cached in CI so it will always run the full suite there. Locally if you're iterating that's why the `test:watch` command is there?

**Comment by kvz** [comment]
Added caching for CI 👌

**Comment by kvz** [comment]
BEFORE:


CleanShot 2024-11-13 at 12 00 34@2x


AFTER:

CleanShot 2024-11-13 at 11 59 29@2x


What is the downside of Turbo that made you rip it out again? I like 40x faster testing

**Pull request merged**
